### ISSUE TITLE
Cannot build/install zsh with kcp

### ISSUE THREAD

**Issue by kanwarplaha** [KaOS-Community-Packages/zsh#1]
When building zsh with kcp, the following error is thrown:
```
Test ./E01options.ztst failed: error output differs from expected as shown above for:
showopt() { setopt | egrep 'localoptions|ksharrays'; }
f1() { setopt localoptions ksharrays; showopt }
f2() { setopt ksharrays; showopt }
setopt kshoptionprint
showopt
f1
showopt
f2
showopt
unsetopt ksh_arrays
Was testing: LOCAL_OPTIONS option
./E01options.ztst: test failed.
```

Online search shows it worked for someone after doing make clean. So, I added it to PKGBUILD just before make in the build section. However, that did not work either.

Any ideas how this can be resolved?

**Comment by bvaudour** [comment]
Thanks for the report. It should be fixed with the commit 3386a27.

**Comment by kanwarplaha** [comment]
Can we reopen this? The build does not fail but now it just hangs at:
```
rm -rf Modules .zcompdump;
exit $stat
./A01grammar.ztst: starting.
```

**Comment by MartinVonReichenberg** [comment]
> Can we reopen this? The build does not fail but now it just hangs at:
> ```
> rm -rf Modules .zcompdump;
> exit $stat
> ./A01grammar.ztst: starting.
> ```



I do not have an option to test it out at the moment . . .

**Comment by bvaudour** [comment]
Confirmed.

I’ll unactivate check for now.

**Comment by bvaudour** [comment]
PKGBUILD is updated.

**Comment by kanwarplaha** [comment]
Thanks for the quick fix👍
